# Generated by Django 2.0.5 on 2019-03-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=40)),
                ('Caddress', models.CharField(max_length=100)),
                ('Cphone', models.CharField(max_length=30)),
                ('Cemail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=30)),
                ('Usex', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=7)),
                ('Uphone', models.CharField(max_length=30)),
                ('Uaddress', models.CharField(max_length=100)),
                ('UAcname', models.CharField(max_length=2)),
                ('Uemail', models.EmailField(max_length=254)),
                ('Ubirthday', models.DateField()),
            ],
        ),
    ]
