# Generated by Django 2.0.5 on 2019-03-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mtitle', models.CharField(max_length=40)),
                ('Mpost', models.CharField(max_length=400)),
            ],
        ),
    ]
