# Generated by Django 2.0.5 on 2019-03-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190306_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='Mrating',
            field=models.IntegerField(default=0),
        ),
    ]
