# Generated by Django 2.0.5 on 2019-03-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190314_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
