# Generated by Django 2.0.5 on 2019-03-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mission_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='Mrating',
            field=models.IntegerField(choices=[(1, '希望改善'), (2, '一般'), (3, '不錯'), (4, '非常好'), (5, '_(:3')], default=5),
        ),
    ]
