# Generated by Django 2.0.5 on 2019-04-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190314_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
