# Generated by Django 2.0.5 on 2019-04-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190408_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='Mname',
            field=models.CharField(default='anonymous', max_length=40),
        ),
    ]
