# Generated by Django 2.0.5 on 2019-04-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_mission_mname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='postime',
            field=models.DateField(auto_now=True),
        ),
    ]
