# Generated by Django 2.0.5 on 2019-04-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_mission_postime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='Mtitle',
            field=models.CharField(default='no title', max_length=40),
        ),
    ]
