# Generated by Django 2.0.5 on 2019-04-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190410_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='nameofaccept',
            field=models.CharField(default='no one want it', max_length=40),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='case',
            field=models.CharField(default='maybe something wrong here', max_length=100),
        ),
    ]
