# Generated by Django 2.0.5 on 2019-04-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190410_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='caseid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mission',
            name='nameofaccept',
            field=models.CharField(default='no one want it', max_length=400),
        ),
    ]
