# Generated by Django 2.0.5 on 2019-04-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190411_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='daysremind',
            field=models.IntegerField(default=0),
        ),
    ]
