# Generated by Django 2.0.5 on 2019-04-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_userdata_daysremind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='nameofaccept',
            field=models.CharField(max_length=400),
        ),
    ]
