# Generated by Django 2.0.5 on 2019-04-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190416_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ImageField(default='haha', upload_to='imgdata'),
        ),
    ]
