# Generated by Django 2.0.5 on 2019-04-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190416_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='Mimage',
            field=models.ImageField(default='haha', upload_to='images'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='address',
            field=models.CharField(default='no address here', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='position',
            field=models.CharField(default='didnt write here', max_length=100),
        ),
    ]
