# Generated by Django 2.0.5 on 2019-04-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190416_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='Mimage',
            field=models.ImageField(default='haha', upload_to='imageformission'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(default='haha', upload_to='imageforcase'),
        ),
    ]
