# Generated by Django 2.0.5 on 2019-04-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190416_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=40)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=40)),
                ('userimage', models.ImageField(default='no image here', upload_to='imageforuser')),
            ],
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='daysremind',
            new_name='daysremain',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='position',
        ),
    ]
