# Generated by Django 2.0.5 on 2019-04-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190426_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='usersave',
        ),
    ]
