# Generated by Django 2.0.5 on 2019-04-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190426_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersave',
            name='username',
            field=models.CharField(default='no one !! wtf', max_length=40, null=True),
        ),
    ]
