# Generated by Django 2.2 on 2019-04-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190426_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersave',
            name='username',
            field=models.CharField(default='no one !! wtf', max_length=40),
        ),
    ]
