# Generated by Django 2.0.5 on 2019-04-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190426_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='usericon',
            field=models.CharField(default='something worng here', max_length=400),
        ),
        migrations.AlterField(
            model_name='usersave',
            name='username',
            field=models.CharField(default='no one !! wtf', max_length=40),
        ),
    ]
