# Generated by Django 2.2 on 2019-04-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190427_0815'),
        ('app', '0025_auto_20190427_1656'),
    ]

    operations = [
    ]
