# Generated by Django 2.0.5 on 2019-05-01 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190427_1656'),
        ('app', '0025_auto_20190427_0815'),
    ]

    operations = [
    ]
