# Generated by Django 2.0.5 on 2019-05-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_merge_20190501_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='uid',
            field=models.IntegerField(default=1),
        ),
    ]
