# Generated by Django 2.2 on 2019-05-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_merge_20190427_1710'),
        ('app', '0027_comments_uid'),
    ]

    operations = [
    ]
