# Generated by Django 2.0.5 on 2019-05-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_comments_uid'),
        ('app', '0026_merge_20190427_1710'),
    ]

    operations = [
    ]
