# Generated by Django 2.0.5 on 2019-05-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_merge_20190503_1245'),
        ('app', '0028_merge_20190502_2117'),
    ]

    operations = [
    ]
