# Generated by Django 2.0.5 on 2019-05-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_mission_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(default='可', max_length=20),
        ),
    ]
