# Generated by Django 2.0.5 on 2019-05-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190503_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='casestatus',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
