# Generated by Django 2.0.5 on 2019-05-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190503_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='Mvideo',
            field=models.FileField(default='haha', upload_to='imageformission'),
        ),
    ]
