# Generated by Django 2.0.5 on 2019-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_mission_mvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='Mimage',
            field=models.ImageField(default='haha.png', upload_to='imageformission'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='Mvideo',
            field=models.FileField(default='haha.png', upload_to='imageformission'),
        ),
    ]
