# Generated by Django 2.0.5 on 2019-05-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190506_0016'),
        ('app', '0029_merge_20190507_2211'),
    ]

    operations = [
    ]
