# Generated by Django 2.0.5 on 2019-05-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20190507_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=400)),
                ('clickrate', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='imageforads')),
                ('video', models.FileField(upload_to='imageforads')),
            ],
        ),
        migrations.AddField(
            model_name='usersave',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
