# Generated by Django 2.0.5 on 2019-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20190508_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='content',
            field=models.CharField(default='some error here', max_length=400),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(default='no image here', upload_to='imageforads'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(default='some error here', max_length=40),
        ),
        migrations.AlterField(
            model_name='ads',
            name='username',
            field=models.CharField(default='some error here', max_length=40),
        ),
        migrations.AlterField(
            model_name='ads',
            name='video',
            field=models.FileField(default='no vid here', upload_to='imageforads'),
        ),
    ]
