# Generated by Django 2.0.5 on 2019-05-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20190508_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersave',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
