# Generated by Django 2.0.5 on 2019-05-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20190508_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='Mpost',
            field=models.TextField(max_length=400),
        ),
    ]
