# Generated by Django 2.0.5 on 2019-05-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190509_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='some error here', max_length=40)),
                ('care', models.IntegerField(default=0)),
                ('carename', models.CharField(default='some error here', max_length=40)),
            ],
        ),
    ]
