# Generated by Django 2.0.5 on 2019-05-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_care'),
    ]

    operations = [
        migrations.RenameField(
            model_name='care',
            old_name='care',
            new_name='carenum',
        ),
    ]
