# Generated by Django 2.0.5 on 2019-05-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20190514_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='careid',
            field=models.IntegerField(default=1),
        ),
    ]
