# Generated by Django 2.0.5 on 2019-05-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_care_careid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='money',
            field=models.CharField(max_length=400),
        ),
    ]
