# Generated by Django 2.0.5 on 2019-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20190515_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersave',
            name='userstatus',
            field=models.CharField(default='普通用戶', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='Mimage',
            field=models.ImageField(default='/image/haha.png', upload_to='imageformission'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='Mvideo',
            field=models.FileField(blank=True, default='/image/haha.png', upload_to='imageformission'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(default='/image/haha.png', upload_to='imageforcase'),
        ),
    ]
