# Generated by Django 2.0.5 on 2019-05-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20190516_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='company',
            field=models.CharField(default='company', max_length=40),
        ),
    ]
