# Generated by Django 2.0.5 on 2019-05-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20190521_2257'),
        ('app', '0048_remove_ads_video'),
    ]

    operations = [
    ]
