# Generated by Django 2.0.5 on 2019-05-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_merge_20190524_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='image',
        ),
    ]
