# Generated by Django 2.0.5 on 2019-05-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_userdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='carebyid',
            field=models.IntegerField(default=1),
        ),
    ]
